CHANGELOG.md, README.md, lib/alertSession.js, lib/alertStateMachine.js, lib/braveAlerter.js, lib/helpers.js, test/integration/testFallbackFlow.js, test/integration/testHappyPath.js, test/unit/testAlertStateMachine.js, test/unit/testBraveAlerter/testBraveAlerterHandleTwilioRequest.js, test/unit/testBraveAlerter/testBraveAlerterSendSingleAlert.js, test/unit/testBraveAlerter/testBraveAlerterStartAlertSession.js
- ODetect's sessions start out with chatbot_state = null. Therefore, when the initial message is sent, it needs to update the chatbot_state to STARTED
- Added `isTestEnvironment` helper method (I don't feel like this is scope creep, but what do you think @schwarrrtz ?)
- Changed the way that I was handling `incidentCategories` to match how PostgreSQL and `ng-pq` handle arrays
- Added a bunch of try/catches
- Updated tests accordingly
=> Fixes needed for integration (CU-bar1zy and CU-bar0fm)

CHANGELOG.md, lib/helpers.js
- So that we can have consistent formatting for console.error output. Most importantly, we wanted to have the timestamp
Please let me know what you think of `logError` as the name of the function. I didn't think that just `helpers.error` was descriptive enough.
=> Add helpers.logError function (CU-jcuw85)

CHANGELOG.md, README.md, lib/helpers.js, package-lock.json, package.json
- Timestamps will be added by the runtime environment (pm2 or kubernetes)
- Added missing documentation for helpers.logError to README
- No longer need `moment-timezone`
=> Remove timestamp from helpers.log and helpers.logError (CU-jcuw85)

CHANGELOG.md, README.md, lib/braveAlerter.js, test/integration/testFallbackFlow.js, test/integration/testHappyPath.js, test/unit/testBraveAlerter/testBraveAlerterSendFallbackMessagesForSession.js, test/unit/testBraveAlerter/testBraveAlerterStartAlertSession.js
- Changed the fallbackToPhoneNumber parameter to an array of strings
instead of a string. It will attempt to send the fallback message
to all of these numbers simultaneously.
- The resulting fallbackReturnMessage will be a comma-separated string of the return values from Twilio. If a particular phone number doesn't send correctly, its value in the comma-separated string will be "no_response"
- Updated tests accordingly
=> Add ability to send multiple fallback messages (CU-pv8hd5)

CHANGELOG.md, lib/braveAlerter.js, test/unit/testBraveAlerter/testBraveAlerterHandleTwilioRequest.js
`handleTwilioRequest` was saying that Bad Requests were in '/', but really they were to `/alert/sms`
Tested this
- Updating the unit tests
- Including it in Buttons https://github.com/bravetechnologycoop/BraveButtons/pull/98 and deploying it to `chatbot-dev`. Then I faked one of these errors by responding to a Button-press alert using a phone that wasn't the Responder phone. This correctly gave me the error message `21|BraveServer  | 2021-05-13 23:23:25.853: Bad request to /alert/sms: Invalid Phone Number`
- Including it in Sensors https://github.com/bravetechnologycoop/BraveSensor-Server/pull/107 and deploying it to `dev.sensors.brave.coop`. Then I faked one of the errors by responding to an alert using a phone that wasn't the Responder phone. This correctly gave me the message …
=> Fix route in API error messages

.vscode/launch.json, CHANGELOG.md
- So that those of us who use VS Code will be able to use it to
debug Mocha tests without any extra work
Some screenshots of how it works from the equivalent change in BraveSensors: https://github.com/bravetechnologycoop/BraveSensor-Server/pull/114/files
=> Add VSCode launch config for debugging Mocha tests

CHANGELOG.md, lib/braveAlerter.js, test/integration/testBraveAlerter/testBraveAlerterHandleGetNewNotificationsCount.js, test/integration/testHappyPath.js, test/unit/testBraveAlerter/testBraveAlerterContructor.js
- added `GET /alert/newNotificationsCount` endpoint to be used by the Alert App
- added and updated tests
I tested this by deploying it to the Buttons dev server and hitting the endpoint with my WIP Alert App code - the number of new notifications renders in the app as expected. I also added integration tests, which pass as expected.
=> added GET /alert/newNotificationsCount endpoint (CU-hjwcwk)

.travis.yml, CHANGELOG.md, audit-ci.json
- This will block the build when there are high or critical security
issues. The build will only pass if these issues are added to the
allowlist in audit-ci.json or fixed.
- :heavy_check_mark: With no changes in the project
- :heavy_check_mark: See in the Travis logs that it ran (https://app.travis-ci.com/github/bravetechnologycoop/brave-alert-lib/builds/232985360)
- :heavy_check_mark: Travis passes
- :heavy_check_mark:  Add a known high severity security issue to the project 
- :heavy_check_mark: See in the Travis logs that it ran (https://app.travis-ci.com/github/bravetechnologycoop/brave-alert-lib/builds/232985564)
- :heavy_check_mark:  Travis fails
=> Add audit-ci to Travis to perform static security checks (CU-121j1qz)

CHANGELOG.md, lib/braveAlerter.js, lib/designateDevice.js, test/integration/testBraveAlerter/testBraveAlerterHandleAcknowledgeAlertSession.js, test/integration/testBraveAlerter/testBraveAlerterHandleGetActiveAlerts.js, test/integration/testBraveAlerter/testBraveAlerterHandleGetHistoricAlerts.js, test/integration/testBraveAlerter/testBraveAlerterHandleGetLocation.js, test/integration/testBraveAlerter/testBraveAlerterHandleGetNewNotificationsCount.js, test/integration/testBraveAlerter/testBraveAlerterHandleIncidentCategory.js, test/integration/testBraveAlerter/testBraveAlerterHandleRespondToAlertSession.js, test/integration/testDesignateDevice.js, test/unit/testBraveAlerter/testBraveAlerterHandleAcknowledgeAlertSession.js, test/unit/testBraveAlerter/testBraveAlerterHandleIncidentCategory.js, test/unit/testBraveAlerter/testBraveAlerterHandleRespondToAlertSession.js
I fixed this for all the other API calls used by the app, but forgot this one because it was in this different file. Basically, the app immediately tries to parse the response as though it were JSON, so by only sending the error message back, instead of seeing the error message, I'd instead get "JSON parse error"  (which is less helpful 😉 )
- :heavy_check_mark: Deploy to chatbot-dev and dev.sensors
- :heavy_check_mark: On my emulator, hit the `POST /alert/designatedevice` endpoint with valid values
- :heavy_check_mark: Logs the API key, repsonder push ID, and verification code on both servers
- :heavy_check_mark: No error message on app
- :heavy_check_mark: On my emulator, hit the `POST /alert/designatedevice` endpoint with valid invalid values (e.g. not provide the API key)
- …
=> Fix JSON return values for designateDevice

CHANGELOG.md, package-lock.json, package.json
- To resolve some moderate security vulnerabilities based on `npm audit` output.
- :heavy_check_mark: Automated tests pass (since the dependencies that were upgraded are only used for tests and linting, I don't think I need to fun any other tests)
=> Update eslint and mocha

.env.example, CHANGELOG.md, README.md, lib/helpers.js
- So that I can better debug transaction/deadlock issues in
production. This will output to the console the start and end of
each SQL query that uses the `runQuery` command (which should be
all of them except for BEGIN, COMMIT, and ROLLBACK)
- :heavy_check_mark: Deploy to Sensors Dev
- :heavy_check_mark: Run smoke tests on Sensors Dev
- :heavy_check_mark: With IS_DB_LOGGING=true
- :heavy_check_mark: With IS_DB_LOGGING=false
- :heavy_check_mark: With IS_DB_LOGGING absent from the .env (should behave as though IS_DB_LOGGING=false)
=> Add DB debug logging that is controlled by an env variable (CU-2atyr1z)

CHANGELOG.md, README.md, lib/alertSession.js, lib/alertStateMachine.js, lib/braveAlerter.js, lib/models/Client.js, lib/models/factories.js, test/integration/testHappyPathTwilio.js, test/testingHelpers.js, test/unit/testAlertStateMachine.js
- Add `language` as a property of the `Client` object
- Take `language` as a parameter where needed so that it can be passed back to Buttons/Sensor code for translation
- :heavy_check_mark: Passes the Buttons tests in https://github.com/bravetechnologycoop/BraveButtons/pull/167
=> Allow client-specific internationalization (CU-2dtutrx)

CHANGELOG.md, README.md, lib/braveAlerter.js, test/integration/testFallbackFlowTwilio.js, test/integration/testHappyPathTwilio.js, test/testingHelpers.js, test/unit/testBraveAlerter/testBraveAlerterContructor.js, test/unit/testBraveAlerter/testBraveAlerterHandleTwilioRequest.js
... to take both the fromPhoneNumber and toPhoneNumber so that we
can find the session with that devicePhoneNumber and
responderPhoneNumber. This will allow us to re-use Twilio numbers
at different clients (assuming the clients have different
responderPhoneNumbers)
- :heavy_check_mark: Passes all the tests in the corresponding Sensors pull request: https://github.com/bravetechnologycoop/BraveSensor/pull/177
- :heavy_check_mark: Passes all the tests in the corresponding Buttons pull request: https://github.com/bravetechnologycoop/BraveButtons/pull/170
=> Change `getAlertSessionByPhoneNumber` name and parameter list (CU-2fk3y8a)

CHANGELOG.md, lib/twilioHelpers.js, test/integration/testTwilioHelpers.js, test/unit/testTwilioHelpers/testBuyAndConfigureTwilioPhoneNumber.js
- It was really annoying not to know why this function failed. We
would have to look into the server logs to find out, this info
is better sent back to the client who can display it in the UI
- :heavy_check_mark: Deploy to Sensors dev
- :heavy_check_mark: Hit the endpoint with an area code that has no available phone numbers (try 600). See error message that says "Error: No phone numbers found"
- :heavy_check_mark: Hit the endpoint with an area code that doesn't exist but is formatted correctly (try 000). See error message that says "Error: Invalid local area code: 000"
- :heavy_check_mark: Hit the endpoint with an area code that isn't formatted correctly (try abc). See error message that syas "Error: Invalid area code: abc"
- :heavy_check_mark: Do not log any of these errors to Sentry
=> Improve error messages when buying Twilio numbers

CHANGELOG.md, README.md, lib/models/Client.js, lib/models/factories.js
- This gives us more fine-grained control over the messages and the display properties of the clients
=> Split Client is_active into is_displayed, is_sending_alerts, is_sending_vitals (CU-860q154rh, CU-860ptt5rp)

CHANGELOG.md, lib/googleHelpers.js, test/testingHelpers.js
This is a minor error that arose when testing the library with real Google ID tokens.
I had not realized that the `Date.now()` function returns the UNIX epoch time in *milliseconds*, whereas the `exp` member of a Google ID token is a UNIX epoch time in *seconds*.
Thus, when using `paGetPayload` on a real Google ID token, `Date.now()` always evaluated to be greater than the `exp` member of a Google ID token; e.g., 123456789000 > 123456789.
This PR updates the usage of `Date.now()` such that it is divided by 1000 to be in seconds, not milliseconds.
It also updates the usage of `Date.now()` in the mock OAuth2Client object and Google ID token factory defined in `testingHelpers.js`. 
Test plan:
=> Fixed usage of Date.now() for paGetPayload

CHANGELOG.md, lib/googleHelpers.js
In the event of an error in googleHelpers.paAuthorize, the response object is never closed / resolved.
This is because it does not end with a '.send()', '.json()', or '.end()'; just 'res.status(401)' or 'res.status(400)'.
This PR fixes that, returning a JSON message giving a brief explanation of the error; 'Unauthorized' or 'Bad request'.
Test plan:
=> Bug fix for googleHelpers.paAuthorize

CHANGELOG.md, README.md, lib/models/Client.js, lib/models/factories.js
This is a continuation of the previously merged [PR](https://github.com/bravetechnologycoop/brave-alert-lib/pull/67), which removes much of the OneSignal code in brave-alert-lib.
=> Remove alertApiKey and responderPushId from Client model and factory functions (CU-86dqkmhza).

CHANGELOG.md, index.js, lib/models/Session.js
This PR moves the Session model from BraveButtons and BraveSensor into brave-alert-lib, by combining and aggregating parts from both. It should work as a drop-in replacement for the versions currently implemented in either repositories.
=> Add Session model (CU-86791yyvg).

CHANGELOG.md, README.md, lib/googleHelpers.js, lib/models/Session.js, test/testingHelpers.js, test/unit/testGoogleHelpers/testPaAuthorize.js
This PR allows PA API routes to be authenticated with the Authorization header, as opposed to submission in the body of a request.
The Authorization header has a 'Bearer' type, where a token can be submitted (as opposed to Basic where a username and password is submitted); thus, the Bearer type is used here.
Test Plan:
=> Authorize with Authorization header (of type Bearer) for googleHelpers.paAuthorize (CU-13kqjz8).

CHANGELOG.md, README.md, lib/models/Session.js
This PR adds `isResettable` to the Session model, which is primarily used for the BraveSensor reset chatbot flow ( [view PR](https://github.com/bravetechnologycoop/BraveSensor/pull/271) ).
Test Plan:
=> Add `isResettable` to Session model (CU-86drfmvrj).
